### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by chrisalbon** [danhammer/ois-incidents#1]
```
Internal Server Error
```

The server has either erred or is incapable of performing the requested operation.

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-        2.5.2/webapp2.py", line 1535, in __call__
        rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~ois-incidents/v1.380966225799834251/api.py", line 32, in get
   json.dumps(_search(query, limit))
  File "/base/data/home/apps/s~ois-incidents/v1.380966225799834251/api.py", line 20, in _search
    res = [x['_source'] for x in es_res['hits']['hits']]
KeyError: 'hits'
```

**Comment by danhammer** [comment]
This was the result of moving the backend to a different (hosted) elasticsearch database.  Fixed.
